name: Self hosted runner

on:
  push:
    branches:
      - main

jobs:
  DeployJob:
    runs-on: codebuild-akhil-self-hosted-gha-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::183149563271:role/MyTurboRole
          aws-region: eu-west-1
      - name: A good step
        run: |
          echo 'New runner'
          curl https://yw3yuoxld5xn5gsahba47j3cwi0qiemv.lambda-url.eu-west-1.on.aws