name: Self hosted runner

on:
  push:
    branches:
      - main

jobs:
  DeployJob:
    runs-on: codebuild-akhil-self-hosted-gha-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: A good step
        run: |
          echo 'Working self hosted GHA'